### ISSUE TITLE
New authentication scheme

### ISSUE THREAD

**Issue by nsoblath** [project8/scarab#108]
Authentication will be revamped to enable loading of authentication parameters from multiple sources, including an auth file (as currently done), environment variables, and the command line.

Authentication information will be loaded in this order:
1. Auth file
2. Environment variables
3. CLI

Authentication will include a schema that will look something like this (using DL as an example):

```
items:
  dripline:
    user:
      required: true <optional; default: false>
      default: dripline <optional; default: ''>
      env: DL_USER <optional; no default>
    password:
      required: true
      default: dripline
      env: DL_PASS
file: my_auths.yaml <optional; default: ''>
```

Anything in the schema can be set during the configuration stage.

For applications in DL, see https://github.com/driplineorg/dripline/issues/27.
